#!bin/bash

####################################################
##       Installs programs I usually install      ##
####################################################

# ##################################################
# git
# ##################################################
sudo apt-get install git -y
if [ -x "$(command -v git)" ];then
    echo "git installed!\n" >&2 >> installLog
    #exit 1
fi

# ##################################################
# vim
# ##################################################
sudo apt-get install vim -y
if [ -x "$(command -v vim)" ];then
    echo "vim install!\n" >&2 >> installLog
    #exit 1
fi

# ##################################################
# tty-clock
# ##################################################
sudo apt-get install tty-clock -y
if [ -x "$(command -v tty-clock)" ]; then
    echo 'tty-clock installed!\n' >&2 >> installLog
    #exit 1
fi

# ##################################################
# dropbox
# ##################################################
sudo apt-get install dropbox -y
if [ -x "$(command -v dropbox)" ]; then
    echo 'dropbox installed!\n' >&2 >> installLog
    #exit 1
fi

# ##################################################
# vlc
# ##################################################
sudo apt-get install vlc -y
if [ -x "$(command -v vlc)" ]; then
    echo 'vlc installed' >&2 >> installLog
    #exit 1
fi

# ##################################################
# neofetch
# ##################################################
sudo apt-get install neofetch -y
if [ -x "$(command -v neofetch)" ]; then
    echo "neofetch installed!\n" >&2 >> installLog
    #exit 1
fi

# ##################################################
# htop
# ##################################################
sudo apt-get install htop -y
if [ -x "$(command -v htop)" ]; then
    echo "htop installed!\n" >&2 >> installLog
    #exit 1
fi

# ##################################################
# pip3 and youtube-dl
# ##################################################
sudo apt-get install python3-pip -y && echo "python3-pip installed!\n" >> installLog
sudo -H pip3 install --upgrade youtube-dl && echo "youtube-dl installed!\n" >> installLog

# ##################################################
# Add .alias to .bashrc
# ##################################################
cat aliasToBashrc >> ~/.bashrc && echo ".alias added to .bashrc" >> installLog
source ~/.bashrc

# ##################################################
# From other sources
# ##################################################
## #################################################
## vim dotfiles, extarnal source
## credit to timss (https://github.com/timss/vimconf)
## vim need to run to finsih the installation
## Is done at the end of the file
## #################################################
cd ~/git
git clone https://github.com/timss/vimconf.git
ln -s ~/git/vimconf/.vimrc ~/.vimrc

# Launching vim, to install extarnal dotfiles
cd ~/ && vim vimTest.txt
